[build]
  # Build command
  command = "cd frontend && npm ci && npm run build"
  
  # Directory to publish
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# SPA redirect rules - important for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
